version: "3"

services:
  app:
    build:
      context: docker
      dockerfile: development/app/Dockerfile
    volumes:
      - .:/var/www/html/

  phpstan:
    image: phpstan/phpstan
    environment:
      - PHPSTAN_PRO_WEB_PORT=11111
    ports:
      - "11111:11111"
    volumes:
      - .:/app/