on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "**"

name: "PHPUnit & Codecov"

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        php-version: [8.1]
        symfony-version: ["5.4.*", "6.0.*", "6.1.*"]
        experimental: [false]

    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup PHP
        uses: shivammathur/setup-php@cf36231a82a1ed07abe22c0bbdf5c637fa9d1648
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, dom, json, libxml, mbstring, pdo_sqlite, simplexml, tokenizer, xml, xmlwriter
          coverage: none
          tools: composer

      - name: Specify symfony version
        uses: jacobtomlinson/gha-find-replace@863001a682308a0a2405e69e645cb0899b5ee64b
        with:
          include: "composer.json"
          find: "^5.4|^6.0"
          replace: "${{ matrix.symfony-version }}"
          regex: false

      - name: "Get composer Cache directory"
        id: composer-cache
        run: |
          echo "composer_cache_output_dir=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV
      #          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache composer dependencies"
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          path: ${{ env.composer_cache_output_dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ matrix.symfony-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-${{ matrix.symfony-version }}
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install composer dependencies"
        uses: php-actions/composer@9908de9a0eb7bc64f3870f46ae6cc6cc619219d8
        with:
          php_version: ${{ matrix.php-version }}
          dev: yes
          args: --no-interaction --no-progress --optimize-autoloader

      - name: "Run tests"
        uses: php-actions/phpunit@6aaad49625029bef919e4974ec4c505e15513e8f
        env:
          CMLIFE_USERNAME: ${{ secrets.CMLIFE_USERNAME }}
          CMLIFE_PASSWORD: ${{ secrets.CMLIFE_PASSWORD }}
          CMLIFE_SESSION_ID: ${{ secrets.CMLIFE_SESSION_ID }}
          CMLIFE_XSRF_TOKEN: ${{ secrets.CMLIFE_XSRF_TOKEN }}
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          php_extensions: ctype dom json libxml mbstring pdo_sqlite simplexml tokenizer xml xmlwriter

  code-coverage:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        php-version: [ 8.1 ]
        experimental: [ false ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup PHP
        uses: shivammathur/setup-php@cf36231a82a1ed07abe22c0bbdf5c637fa9d1648
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, dom, json, libxml, mbstring, pdo, simplexml, tokenizer, xdebug, xml, xmlwriter
          coverage: xdebug
          tools: composer

      - name: "Get composer Cache directory"
        id: composer-cache
        run: |
          echo "composer_cache_output_dir=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV
#          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache composer dependencies"
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          path: ${{ env.composer_cache_output_dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install composer dependencies"
        uses: php-actions/composer@9908de9a0eb7bc64f3870f46ae6cc6cc619219d8
        with:
          php_version: ${{ matrix.php-version }}
          dev: yes
          args: --no-interaction --no-progress --optimize-autoloader

      - name: "Run tests"
        uses: php-actions/phpunit@6aaad49625029bef919e4974ec4c505e15513e8f
        env:
          CMLIFE_USERNAME: ${{ secrets.CMLIFE_USERNAME }}
          CMLIFE_PASSWORD: ${{ secrets.CMLIFE_PASSWORD }}
          CMLIFE_SESSION_ID: ${{ secrets.CMLIFE_SESSION_ID }}
          CMLIFE_XSRF_TOKEN: ${{ secrets.CMLIFE_XSRF_TOKEN }}
          XDEBUG_MODE: coverage
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: ctype dom json libxml mbstring pdo simplexml tokenizer xml xmlwriter xdebug
          configuration: .github/workflows/phpunit.xml.dist

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@49f7c0ab9cb38ef2ebb2df7fcbcc7924ca77ad44
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true