on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "**"

name: "PHPStan & Psalm"

jobs:
  code-check-phpstan:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        php-version: [8.1]
        experimental: [false]

    steps:
      - name: "Checkout"
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup PHP
        uses: shivammathur/setup-php@690cb7c9d81dbfe51eba732cfca0a00ca42db777
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, dom, json, libxml, mbstring, pdo_sqlite, simplexml, tokenizer, xml, xmlwriter
          coverage: none
          tools: composer

      - name: "Get composer Cache directory"
        id: composer-cache
        run: |
          echo "composer_cache_output_dir=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV
      #          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache composer dependencies"
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ${{ env.composer_cache_output_dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install composer dependencies"
        uses: php-actions/composer@38e159b1d594d722354e03beaa39e1beca3dc419
        with:
          php_version: ${{ matrix.php-version }}
          dev: yes
          args: --no-interaction --no-progress --optimize-autoloader

      - name: "Run tests"
        uses: php-actions/phpstan@1446415c77df7b2d720e36558717939be1a64938
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: ctype dom json libxml mbstring pdo simplexml tokenizer xml xmlwriter
          configuration: phpstan.neon
          memory_limit: 512M

  code-check-psalm:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        php-version: [ 8.1 ]
        experimental: [ false ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: Setup PHP
        uses: shivammathur/setup-php@690cb7c9d81dbfe51eba732cfca0a00ca42db777
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, dom, json, libxml, mbstring, pdo_sqlite, simplexml, tokenizer, xml, xmlwriter
          coverage: none
          tools: composer

      - name: "Get composer Cache directory"
        id: composer-cache
        run: |
          echo "composer_cache_output_dir=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV
      #          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache composer dependencies"
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ${{ env.composer_cache_output_dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install composer dependencies"
        uses: php-actions/composer@38e159b1d594d722354e03beaa39e1beca3dc419
        with:
          php_version: ${{ matrix.php-version }}
          dev: yes
          args: --no-interaction --no-progress --optimize-autoloader

      - name: "Run a static analysis with vimeo/psalm"
        run: |
          vendor/bin/psalm --config=psalm.xml --output-format=github --show-info=false --stats --threads=$(nproc) --shepherd