on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "**"

name: "PHPStan & Psalm"

jobs:
  code-check-phpstan:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        php-version: [8.1]
        experimental: [false]

    steps:
      - name: "Checkout"
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Setup PHP
        uses: shivammathur/setup-php@2b77dd6b79c3203adc3e3809cde9687bf5834238
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, dom, json, libxml, mbstring, pdo_sqlite, simplexml, tokenizer, xml, xmlwriter
          coverage: none
          tools: composer

      - name: "Get composer Cache directory"
        id: composer-cache
        run: |
          echo "composer_cache_output_dir=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV
      #          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache composer dependencies"
        uses: actions/cache@87396fe6b4d327202df854ff5b3e0a4ea3d77ac6
        with:
          path: ${{ env.composer_cache_output_dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install composer dependencies"
        uses: php-actions/composer@da5a2cb77d99e639acfee65b60a70332793fcd6f
        with:
          php_version: ${{ matrix.php-version }}
          dev: yes
          args: --no-interaction --no-progress --optimize-autoloader

      - name: "Run tests"
        uses: php-actions/phpstan@9a3628e7fe886e0a95d0d0a966ecaddee9ecd93a
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: ctype dom json libxml mbstring pdo simplexml tokenizer xml xmlwriter
          configuration: phpstan.neon
          memory_limit: 512M

  code-check-psalm:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        php-version: [ 8.1 ]
        experimental: [ false ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Setup PHP
        uses: shivammathur/setup-php@2b77dd6b79c3203adc3e3809cde9687bf5834238
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype, dom, json, libxml, mbstring, pdo_sqlite, simplexml, tokenizer, xml, xmlwriter
          coverage: none
          tools: composer

      - name: "Get composer Cache directory"
        id: composer-cache
        run: |
          echo "composer_cache_output_dir=dir::$(composer config cache-files-dir)" >> $GITHUB_ENV
      #          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache composer dependencies"
        uses: actions/cache@87396fe6b4d327202df854ff5b3e0a4ea3d77ac6
        with:
          path: ${{ env.composer_cache_output_dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install composer dependencies"
        uses: php-actions/composer@da5a2cb77d99e639acfee65b60a70332793fcd6f
        with:
          php_version: ${{ matrix.php-version }}
          dev: yes
          args: --no-interaction --no-progress --optimize-autoloader

      - name: "Run a static analysis with vimeo/psalm"
        run: |
          vendor/bin/psalm --config=psalm.xml --output-format=github --show-info=false --stats --threads=$(nproc) --shepherd